# Generated by Django 3.2.3 on 2021-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('date_proposed', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('estimated_budget', models.CharField(max_length=200)),
                ('participant_no', models.CharField(max_length=200)),
                ('target_participant', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('lastname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('officer_no', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=200)),
                ('adviser', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('evaluation_report', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('lastname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('student_no', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
    ]
